zlab_jobeet_homepage:
    pattern:  /
    defaults: { _controller: ZlabJobeetBundle:Job:index }

ZlabJobeetBundle_zlab_job:
        resource: "@ZlabJobeetBundle/Resources/config/routing/job.yml"
        prefix:   /job
