zlab_jobeet_homepage:
    pattern:  /
    defaults: { _controller: ZlabJobeetBundle:Job:index }

ZlabJobeetBundle_zlab_job:
        resource: "@ZlabJobeetBundle/Resources/config/routing/job.yml"
        prefix:   /job
zlabJobeetBundle_category:
    pattern:  /category/{slug}/{page}
    defaults: { _controller: ZlabJobeetBundle:Category:show, page: 1 }
