parameters:
#    zlab_jobeet.example.class: Zlab\JobeetBundle\Example

services:
#    zlab_jobeet.example:
#        class: %zlab_jobeet.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
